### ISSUE TITLE
Refactor point.py with dataclasses and / or getter/setter

### ISSUE THREAD

**Issue by awarebayes** [Mansurow/IU7-w-2020#1]
Hello, upon coming upon your repository I couldnt help but notice a small mischief in point.py class within lab2 of Comutational Algorithms.
You could instead opt in to use dataclasses for such simple types like this one

```
@dataclass 
class Point:
     x: float
     y: float
```

**Comment by Mansurow** [comment]
Hey, i know about OOP but i do it for me not u! If u want change this
class, please copy my class and change how u wish...

вт, 15 мар. 2022 г., 11:24 Mikhail Scherbina ***@***.***>:

**Comment by Mansurow** [comment]
That's good idea. 💡
